### ISSUE TITLE
Set-Up KanBan Board

### ISSUE THREAD

**Issue by Ogaga01** [Ogaga01/Recipe-App#18]
## Hello Reviewer 👋 
In this project milestone, we have implemented the following project requirements:
- Set up the project's KanBan board
- Assign tasks to each member of the group
- Assign group tasks to both members

@Yazino12 is Team member 2
@Ogaga01 is Team member 1

Project link: https://github.com/users/Ogaga01/projects/1

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Ogaga01 and @Yazino12,

Good job so far!
✔️ Tasks are assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] While you are at liberty to divide the tasks as you wish or add any number of tasks that help you build the project, you are still required to have tasks that describe the **specific** tasks detailed in the requirements. From the image, I can only find the task for adding new food. I cannot find any other task that caters to the rest. Kindly review your task descriptions on the Kanban

  ![food-list](https://user-images.githubusercontent.com/36542986/187171666-19a4f19d-c567-4a0b-9c00-5bddb0e4f56c.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dasileker** [comment]
### **Hi @Ogaga01,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
